### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mawkish** [Cyborgscode/Personal-Voice-Assistent#1]
It looks like I've got it installed, though I haven't tested it yet. I thought I'd mention a few clarifications you might want to make to the installation instructions.

In this bit:

```sh
cd /usr/share/pva
clone the repo content here 
mv etc/pva /etc/
```
... you might want to mention whether or not the contents of the repo should be in /usr/share/pva, or whether the repo itself should be there. Though maybe it doesn't make any difference.

In this bit here:

```sh
mkdir -p /usr/local/sbin
cp *say /usr/local/sbin 
```

I think you mean `cp usr/local/sbin/*say /usr/local/sbin`.

Also, you'll want to chmod a bunch of files: pva, pvatrayicon.py, and all the "say" scripts.

Also, I think the pva script tries to grep for ~/.config/pva/pva.conf even when it doesn't exist yet.

Mmm, looks like I haven't go it installed. Maybe I messed something up. The pva script tries to run pva.py, but it's not there.

**Comment by Cyborgscode** [comment]
Thx for your report.

A)

the content of the repo needs to be in /usr/share/pva .  You could just download the github zip and unpack it there.

A development REPO itself should be located somewhere else. 

B) 

My mistake, the say scripts have already been moved into the correct subdirectory . 

I clarified both parts in the README.txt 

C)

"Also, I think the pva script tries to grep for ~/.config/pva/pva.conf even when it doesn't exist yet."

This parts auto-corrects itself on the first run of PVA.java, as this file will be created on exit. 

D)  missing pva.py 

args.. that one is tricky.. the file we need to modify is shipped by VOSK itself. I had mentioned how to modify this in my blog, but forgot to put that part in the README.TXT . I added the modfied version to the repo, you should be able to run pva now.
