### ISSUE TITLE
Cannot install via Repo (GPG Key Error: 404)

### ISSUE THREAD

**Issue by orianflaust** [Cyborgscode/Personal-Voice-Assistent#13]
Hey you all :)

i wanted to install the Personal-Voice-Assistent on my Fedora 36 machine, using the Yum Repo.

> Pakete werden heruntergeladen:
> [SKIPPED] espeak-1.48.04-22.fc36.x86_64.rpm: Already downloaded                                                                           
> [SKIPPED] gtts-2.2.2-4.fc36.noarch.rpm: Already downloaded                                                                                
> [SKIPPED] python3-gtts-2.2.2-4.fc36.noarch.rpm: Already downloaded                                                                        
> [SKIPPED] python3-gtts-token-1.1.4-5.fc36.noarch.rpm: Already downloaded                                                                  
> [SKIPPED] python3-pyaudio-0.2.11-13.fc36.x86_64.rpm: Already downloaded                                                                   
> [SKIPPED] ttmkfdir-3.0.9-65.fc36.x86_64.rpm: Already downloaded                                                                           
> [SKIPPED] xorg-x11-fonts-Type1-7.5-33.fc36.noarch.rpm: Already downloaded                                                                 
> [SKIPPED] java-17-openjdk-17.0.4.0.8-1.fc36.x86_64.rpm: Already downloaded                                                                
> [SKIPPED] pva-base-1-9.x86_64.rpm: Already downloaded                                                                                     
> [SKIPPED] pva-vosk-model-de-large-1-2.x86_64.rpm: Already downloaded                                                                      
> Paketquellenschlüssel für pva wird unverschlüsselt von http://repo.linux-am-dienstag.de:80/RPM-GPG-KEY-fedora-36-x86_64 abgerufen
> PVA 36 - x86_64                                                                                            1.2 kB/s | 196  B     00:00    
> Status code: 404 for http://repo.linux-am-dienstag.de:80/RPM-GPG-KEY-fedora-36-x86_64 (IP: 83.246.80.133)
> Die heruntergeladenen Pakete wurden bis zur nächsten erfolgreichen Transaktion im Zwischenspeicher abgelegt.
> Sie können zwischengespeicherte Pakete mit dem Befehl »dnf clean packages« entfernen.
> 

Could you please fix that?

Would be really nice because i prefer installing Stuff as proper package, not manually.

Greetings from Germany

**Comment by Cyborgscode** [comment]
thx for reporting.. fixed.
