### ISSUE TITLE
FR: pc zustand überwachen / watchdog for load, diskspace etc.

### ISSUE THREAD

**Issue by Cyborgscode** [Cyborgscode/Personal-Voice-Assistent#15]
Goal: notice user if pc is overloading ( load / cpucores > 1 ) 
Goal: alert user if diskspace dramatically dropping if below a threshold.

**Comment by Cyborgscode** [comment]
ggf. noch remote Überwachungsmodule dranhängen..

**Comment by Cyborgscode** [comment]
Schritt 1: Loadüberwachung hinzugefügt.

**Comment by Cyborgscode** [comment]
PLUGIN SYSTEM added / hinzugefügt

NOW IS YOUR TIME GUYS ... WRITE PLUGINS \o/

**Comment by Moini** [comment]
> PLUGIN SYSTEM added / hinzugefügt
> 
> NOW IS YOUR TIME GUYS ... WRITE PLUGINS \o/

That's cool, but how? Are there instructions anywhere?

**Comment by Cyborgscode** [comment]
Yes, in the README.md inside /plugins/  and you can use LoadTask as a base if you like.

**Comment by Cyborgscode** [comment]
Diskspace warning added.
