### ISSUE TITLE
Launched programs don't show up

### ISSUE THREAD

**Issue by Moini** [Cyborgscode/Personal-Voice-Assistent#16]
Hi,

when I ask Carola (or Mortimer, rather) to start another program for me, the program is not launched in any visible way. 

E.g. I say

Mortimer, öffne Inkscape.

and it replies that it opens the program inkscape.

ps -A
tells me that inkscape is running.

168319 pts/0    00:00:00 inkscape

The pts/0 is different from how other programs show up in the list - for other GUI programs, I get a '?' instead.

But Inkscape is not visible on my monitor.

Same goes for screenshots - no GUI appears for my flameshot.

Searching something on the web works, though - weather report and time announcing, too. Haven't tested the files part, as I'm not sure how that would work with my folder structure etc.

Sometimes, when I kill pva, the app then shows up on my monitor after Mortimer is 'dead'.

How can I debug this? What could be the cause? (thread, screen, ...)

-----------

Note that I have put Mortimer in a custom directory, and did not add it into /usr/, /etc/ etc. Instead, I've adjusted all those little paths everywhere before compiling. It runs without problems now, even though it wouldn't stop reading a file to me instead of a greeting until I hardcoded the greeting path.

Would be cool if the paths weren't hardcoded but in a variable, e.g. in the compile script... would be so much easier (and less error-prone) to adjust.

I'm running it on Linux Mint, based on the older LTS 20.04.

**Comment by Moini** [comment]
Btw. a .gitignore would be great. It tries tracking all those compiled Java files.

**Comment by Moini** [comment]
... some of them already ended up in the repository, e.g. https://github.com/Cyborgscode/Personal-Voice-Assistent/tree/main/hash

**Comment by Cyborgscode** [comment]
PVA just starts the app, if it doesn't wanne open a window, it's up to the app. I don't think I can help you here.

Those Classfiles are there, because I uploaded them to make it easier for people without a JAVAC to start up the app.
As we did change a lot, i think i will remove them, so thanks for the hint.

**Comment by Cyborgscode** [comment]
PVA.java -> Exec()

**Comment by Cyborgscode** [comment]
regarding your app startup issue.. A thought: if pva isn't started in the desktop environment, your won't get windows.

**Comment by Moini** [comment]
Thanks, yes, I was going to try out whether using https://docs.oracle.com/javase/1.5.0/docs/api/java/lang/ProcessBuilder.html and logging the environment that's passed in gives me a different result / a hint.

**Comment by Cyborgscode** [comment]
don't be so complicated:

```
#!/bin/bash

strings /proc/self/environ >> /tmp/debug.log
APPNAME
```

**Comment by Cyborgscode** [comment]
Did you solve it?

**Comment by Moini** [comment]
I haven't retried yet, sorry. Planning to do so next year ;-)

**Comment by Cyborgscode** [comment]
Any News?

**Comment by Moini** [comment]
Nothing new as of yet. I'm dreading the work it will take to keep it saved in a non system directory when I update it from the repository. /usr/bin ... and /etc/ ... are hardcoded everywhere.

**Comment by Moini** [comment]
I've tried it again with the non-updated version.

Findings:

* planting the command 'strings /proc/self/environ >> /tmp/debug.log' in the 'pva' file returns :0.0 for 'DISPLAY', just like it does on the terminal, where starting Inkscape works
* saying 'öffne sozi' works and opens sozi in the foreground
* saying 'öffne inkscape' makes Inkscape show up in the task manager
* using the custom command 'inkscape &' makes the modified command show up in the task manager
* using 'inkscape --gui' doesn't change anything, either.
* Trying to make Inkscape log something to /tmp by using 'inkscape &> /tmp/inklog.txt' does not even create a log file, but the changed command shows up in the taskmanager
* Killing or closing pva while Inkscape (that is not visible) is running, results in Inkscape suddenly showing up 

Don't know what else to try. Seems pva is in some way blocking Inkscape. It's also not because of the pythonenv I have it running in, tried that in terminal... Other programs do not seem affected. I was not able to start Krita, it always understood 'Kreta'. Seems to ignore the contextreplacement thing there. 

Not sure it's worth pursuing this. Thank you for all the suggestions, though!

**Comment by Cyborgscode** [comment]
honestly, sounds like an inkscape issue to me.
