### ISSUE TITLE
Install rpm repository

### ISSUE THREAD

**Issue by Denis4l** [Cyborgscode/Personal-Voice-Assistent#20]
Chuss,
So I tried to install the repo : 

`mkdir -p /etc/yum.repos.de/
vim /etc/yum.repos.de/pva`

Then copy and paste your code, close vim and then
`dnf makecache --repofrompath pva,/etc/yum.repos.de/`
But dnf complains : 

```
Errors during downloading metadata for repository 'pva':
- Curl error (37): Couldn't read a file:// file for file:///etc/yum.repos.de/repodata/repomd.xml [Couldn't open file /etc/yum.repos.de/repodata/repomd.xml]
Error: Échec du téléchargement des métadonnées pour le dépôt « pva » : Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Dépôts ignorés : pva
```
I've missed something ?

**Comment by Cyborgscode** [comment]
Hi,

it depends: Which Fedora release do you use?

**Comment by Denis4l** [comment]
Fedora 38

**Comment by Cyborgscode** [comment]
try again.

**Comment by Cyborgscode** [comment]
F38 was not in the repo .. i added f39 and 40 now..

**Comment by Denis4l** [comment]
Thanks. Nothing changed. Do need more info ?

**Comment by Cyborgscode** [comment]
keys have been missing too.

**Comment by Denis4l** [comment]
Shall I do something ?

**Comment by Cyborgscode** [comment]
Yes, testing it again, as there is nothing more i could do on the repo side.

**Comment by Denis4l** [comment]
Bad news, still the same. 
I do not understand anything in this, but it complains there is no file /repodata/repomd.xml ; indeed there's even not a directory «repodata». You do not ask to make one in the readme.md
I have tried to put the pva file into /etc/yum.repos.d/ where are other files, instead of /etc/yum.repos.de/ but it is the same (obviously but at least I tried).

**Comment by Cyborgscode** [comment]
"/etc/yum.repos.de/" is just wrong. It must be "/etc/yum.repos.d/" .  In this directory is just the .repo file, nothing more. All repo data is downloaded to "/var/cache/dnf/{repoid-hash}/...". 

I have btw. no idea what "dnf makecache --repofrompath pva,/etc/yum.repos.de/" should do. This is the correct procedure:

dnf makecache --repo=pva
dnf install pva-base pva-vosk-model-de-small

which can't work with the "yum.repos.de" typo I made in the docs. Thanks for reporting this.

**Comment by Denis4l** [comment]
Haaaa :+1:  Good then it works like this ( sorry but I think you may change your readme file like this : 
1- create the file /etc/yum.repos.d/pva.repo (it is obvious that it must be a .repo file... but better to write it ;)
2 - sudo sudo dnf makecache --repo=pva
3 - sudo dnf install pva-base pva-vosk-model-de-small

Now I have to install the french version (I had a look on the issue 5 cause I had the same doubts).
