### ISSUE TITLE
The readme is unreadable

### ISSUE THREAD

**Issue by Samisafool** [Cyborgscode/Personal-Voice-Assistent#5]
Please change the file format to markdown (A simple rename to README.md will do) to get a better font and use markdown headings:

**Text**:
`COMMANDS`

**Markdown**:
# Commands:

```md
**Text**:
`COMMANDS`

**Markdown**:
# Commands:
```

And I will fix your readme if you want

**Comment by Cyborgscode** [comment]
"unreadable" is a bit harsh ;) I transfered your README changes.thx.

**Comment by Samisafool** [comment]
It wasn't an insult lol, but on github the font is too small for me

**Comment by Samisafool** [comment]
And please revert, I stated that the changes were WIP (Work in Progress)
